### ISSUE TITLE
CORS policy bug

### ISSUE THREAD

**Issue by MichaelHopwood** [mantzaris/TagasaurusExportAnalysis#1]
```Access to script at 'file:///E:/UCF/Dissertation/TagasaurusExportAnalysis/network-visualization1.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.```

**Potential fixes**

https://www.pmichaels.net/tag/access-to-script-at-from-origin-null-has-been-blocked-by-cors-policy-cross-origin-requests-are-only-supported-for-protocol-schemes-http/

https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local

https://www.codeproject.com/Questions/1195078/How-to-fix-cross-origin-requests-are-only-supporte

**Comment by mantzaris** [comment]
Where did that error come from? Using the recent pushed commit?
